apiVersion: apps/v1
kind: Deployment
metadata:
  name: two
  labels:
    app: two-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: two-nginx
  template:
    metadata:
      labels:
        app: two-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
